(define (cont-frac n d k l)
     (display l)
     (newline)
     (if (= l k)
      (n l)
      (if (= l 1)
      (/ (n l) (+ (d (- l 1)) (/ (n l) (cont-frac n d k (+ l 1)))))
      (+ (d (- l 1)) (/ (n l) (cont-frac n d k (+ l 1)))))))  
(cont-frac (lambda (i) 1.0) (lambda (i) 1.0) 10 1)
