(define (product term a next b)
       (if (> a b)
        1
        (* (term a) (product term (next a) next b))))
(define (sqr x) (* x x))
(define (piapp n)
     (define (nex x) (+ x 2))
     (define d (if (= (remainder n 2) 0)
     (- n 1)
     (- n 2)))
     (* (/ (/ (product sqr 2 nex (- n 1)) 2) (/ (product sqr 3 nex n) d)) 4))
